on:
  workflow_call:
    inputs:
      artifact-download:
        required: false
        type: boolean
        default: false
      artifact-id:
        required: false
        type: string
      artifact-download-dir:
        required: false
        type: string
      dockerfile-path:
        required: false
        type: string
      docker-metadata-flavor:
        required: false
        type: string

jobs:
  package-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        if: ${{ inputs.artifact-download }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-id }}
          path: ${{ inputs.artifact-download-dir }}

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, label) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: ${{ inputs.docker-metadata-flavor }}

      - name: Build an push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile-path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
